### ISSUE TITLE
fix: the application cannot be deployed on platforms like Vercel

### ISSUE THREAD

**Issue by JheysonSaavedr4** [NextChatORG/nextchat-web#27]
This problem is due to the way we implement SSR.
The application must use SSR, but because it's open source, it must also be able to be deployed on popular platforms such as Vercel and not only on servers with NodeJS (as it's currently), this problem must be resolved before the first beta version and it's not a high priority.

**Comment by TeoDev1611** [comment]
Se podría crear un archivo sh en el cual hariamos las ordenes a hacer en el deploy usando node ? esa sería una sugerencia si no tendriamos que ver si usamos nuxt mejor para así más fácil avanzar con el deploy ejemplo [aquí](https://stackoverflow.com/questions/62697183/nuxt-ssr-on-vercel-zeit-now-how-to-deploy)

**Comment by JheysonSaavedr4** [comment]
Currently the problem is that we can only configure the SSR for Vercel using the serverless functions

**Comment by JheysonSaavedr4** [comment]
The specific problem with Vercel is not very difficult to solve, it is only to add a serverless function that serves all the routes as we already do with express
